var demos = {
  rolio: 'Rolio',
  globe: 'Globe',
  countries: 'Countries',
  touch: 'Touch',
  curtains: 'Curtains',
  'test-circle-square': 'Shapes',
  walking: 'Walking',
  'bounce-timing-function': 'Bounce',
  breakout: 'Breakout',
  rhythm: 'Rhythm',
  starfield: 'Starfield',
  snowfall: 'Snowfall',
  'components/web-animations-tools/wat-wat': 'wat',
  'components/web-animations-tools/wat-bezier': 'Bezier',
  'components/web-animations-tools/wat-step': 'Step',
  'components/web-animations-tools/wat-keyframe-inspector': 'Keyframes',
  'components/web-animations-tools/wat-tree': 'TreeView',
  'components/web-animations-tools/wat-timeline': 'Timeline',
  'components/web-animations-tools/wat-player-controls': 'Controls',
};
